version: '3.8'
services:

  postgres:
    build:
      context: postgres/
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespass
    networks:
      - postgres-network

networks:
 postgres-network:
    driver: bridge

volumes:
  postgres: